AllCops:
  TargetRubyVersion: 2.1

Lint/RescueException:
  Exclude:
    - 'lib/rack_json_logger.rb'

Metrics/AbcSize:
  Max: 43

Metrics/BlockLength:
  Max: 28
  Exclude:
    - '*.gemspec'
    - 'spec/**/*'

Metrics/ClassLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/LineLength:
  Max: 160

Metrics/MethodLength:
  Max: 20

Metrics/ParameterLists:
  Max: 6

Metrics/PerceivedComplexity:
  Max: 9

Style/AlignParameters:
  Exclude:
    - 'spec/**/*'

Style/AndOr:
  EnforcedStyle: conditionals

Style/ClassAndModuleChildren:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: semantic
  IgnoredMethods: [lambda, proc, it, specify, before, after, error]

Style/CharacterLiteral:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'lib/**/*'

Style/FormatString:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/ParallelAssignment:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%": "()"
    "%i": "[]"
    "%I": "[]"
    "%q": "()"
    "%Q": "()"
    "%r": "{}"
    "%s": "()"
    "%w": "[]"
    "%W": "[]"
    "%x": "()"

Style/RegexpLiteral:
  Exclude:
    - 'Guardfile'

Style/SignalException:
  EnforcedStyle: semantic

Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/WordArray:
  Enabled: false
